<?php

return [
    "SUPER_ADMIN_EMAIL" => env("SUPER_ADMIN_EMAIL"),
    "SUPER_ADMIN_PASSWORD" => env("SUPER_ADMIN_PASSWORD"),
    "ADMIN_PASSWORD" => env("ADMIN_PASSWORD"),
    "SUPER_ADMIN_USERNAME" => env("SUPER_ADMIN_USERNAME")
];
